### ISSUE TITLE
Running combined.analysis with 4 replicates

### ISSUE THREAD

**Issue by adam-rabinowitz** [deWitLab/peakC#1]
When running combined analysis, with four replicates, I receive a warning message which I think relates to the creation of the 'dbR' data.frame within the output list. I am using version 0.2 of the software. Is the output 'dbR' data.frame being created correctly?

This error can be replicated using the dataset within the tutorial.

data <- peakC::readMultiColumnFile(
  "~/data/Hba_cis.txt",
  vp.pos = 32189804,
  window=300e3
)
res <- peakC::combined.analysis(
  data=data,
  num.exp = 4,
  vp.pos = c(32182969,32196638),
  wSize = 5
)

I get the following warning message as follows:

Warning message:
In merge.data.frame(data.m, data[[i]], by = 1) :
  column names ‘frag_score.x’, ‘frag_score.y’ are duplicated in the result

**Comment by deWitLab** [comment]
Hi Adam,

Thanks for your comment. Note that this is not an error message, but a warning. I tried to run the code myself and it generates the proper output. 

The warning is annoying, though. We will see if we can add code that will prevent it.
The following code should fix it:
``for( i in 1:4){ names(data[[i]])[2] <- letters[i] }``


Best,
Elzo
