### ISSUE TITLE
readqWig error

### ISSUE THREAD

**Issue by tamerbio** [deWitLab/peakC#2]
Hi,
I am trying to Run:
`data <- readqWig("CM_WIN21.wig.gz", vp.pos=57331705, window=700e3)`
but I am getting the following error:
```
Error in scan(file, skip = 2, quiet = T) : 
  scan() expected 'a real', got 'variableStep'
```
what could be possibly wrong? 
Thanks much
TA

**Comment by deWitLab** [comment]
Hi,
Thanks for using peakC. Can you send me the first 10 lines of your wig file and maybe compare them to the example wig files?

Thanks.

Best,
Elzo

Op 7 jan. 2020 om 14:27 heeft tamerbio <notifications@github.com> het volgende geschreven:

﻿

Hi,
I am trying to Run:
data <- readqWig("CM_WIN21.wig.gz", vp.pos=57331705, window=700e3)
but I am getting the following error:

Error in scan(file, skip = 2, quiet = T) :
  scan() expected 'a real', got 'variableStep'


what could be possibly wrong?
Thanks much
TA

**Comment by tamerbio** [comment]
here you are:
```
browser position chr8:56331705-58331705
track type=wiggle_0 name=ESC visibility=full autoScale=off  viewLimits=0.0:2500.0 maxHeightPixels=50:50:8 color=0,0,200  priority=10
variableStep chrom=chr8 span=100
3011333	0
3075005	0
3086281	0
3090288	0
3094786	0
3098820	0
3100566	0

```

**Comment by tamerbio** [comment]
Thanks much. I figured out the problem. the first line has to be removed. but why it show up in the wig file initially?
TA

**Comment by deWitLab** [comment]
Great! I sent a response, but it did not end up in the system apparently... The first line is not one that is in the standard Wig format, but is used by the UCSC genome browser.
