### ISSUE TITLE
Can peakC be used to identify inter-chromosomal interaction?

### ISSUE THREAD

**Issue by CreataNameIsHard** [deWitLab/peakC#3]

**Comment by deWitLab** [comment]
Hi,

Unfortunately peakC cannot be used to identify interchromosomal contacts. Please see the supplementary data of our Methods paper (Splinter et al 2012) if you want analyze interactions in trans: https://www.ncbi.nlm.nih.gov/pubmed/22609568

**Comment by CreataNameIsHard** [comment]
> Hi,
> 
> Unfortunately peakC cannot be used to identify interchromosomal contacts. Please see the supplementary data of our Methods paper (Splinter et al 2012) if you want analyze interactions in trans: https://www.ncbi.nlm.nih.gov/pubmed/22609568

Thank you！I will try that.
